### ISSUE TITLE
If there is a BR backup --s3.endpoint command is brought `/`, the backup will fail

### ISSUE THREAD

**Issue by jacktd9** [pingcap/br#1162] opened 2021-06-01 04:05 UTC
Please answer these questions before submitting your issue. Thanks!

The s3 compatible storage is Minio S3 or HCP S3.

**Failed command**
Error info `failed to put object Request ID: None Body` 
```
export AWS_ACCESS_KEY_ID=${AccessKey}
export AWS_SECRET_ACCESS_KEY=${SecretKey}
./br backup full --pd http://192.168.1.1:2379 --storage "s3://tidb/br20210528_full/" --send-credentials-to-tikv=true --s3.endpoint "http://192.168.1.1:9000/" 
Detail BR log in /tmp/br.log.2021-05-31T23.58.09+0800 
Full backup <............................................................................................................................................................................> 0.00%
Error: msg:"Io(Custom { kind: Other, error: \"failed to put object Request ID: None Body: <?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at //tidb/br20210528_full/7_58213_1592_91da88fe2a00123564e3b657c69a8e290a2e3c9d3c87227a7504138f5df0a06f_1622476689590_write.sst</Message><Resource>//tidb/br20210528_full/7_58213_1592_91da88fe2a00123564e3b657c69a8e290a2e3c9d3c87227a7504138f5df0a06f_1622476689590_write.sst</Resource><RequestId></RequestId><HostId>83dbe45f-2508-4af3-9cf1-30f77f762c61</HostId></Error>\" })" : [BR:KV:ErrKVUnknown]unknown tikv error
```
**Successful command**
```
export AWS_ACCESS_KEY_ID=${AccessKey}
export AWS_SECRET_ACCESS_KEY=${SecretKey}
./br backup full --pd http://192.168.1.1:2379 --storage "s3://tidb/br20210528_full/" --send-credentials-to-tikv=true --s3.endpoint "http://192.168.1.1:9000" 
Detail BR log in /tmp/br.log.2021-05-31T23.59.10+0800 
Full backup <-------------------------..................................................................................................................................................> 14.33%
```
**different**
If the command is brought `/` backup will fail
```
Successful 
--s3.endpoint "http://192.168.1.1:9000" 
Failed 
--s3.endpoint "http://192.168.1.1:9000/" 
```

1. What did you do?
Run backup

2. What did you expect to see?
Backup success

3. What did you see instead?
Backup fail

4. What version of BR and TiDB/TiKV/PD are you using?
TiDB cluster v4.0.10
BR v4.0.10 & v4.0.12

**Comment by kennytm** [comment] 2021-06-01 04:14
duplicate of #992

**Closed by kennytm** 2021-06-01 04:14 UTC
Labels: type/bug
