### ISSUE TITLE
BR require breakcheckpoint resume

### ISSUE THREAD

**Issue by WentaoJin** [pingcap/br#580] opened 2020-11-03 07:58 UTC
BR, as a large data volume physical backup and recovery tool, requires a breakpoint resumable function, otherwise it will be disconnected due to some abnormal external factors（for example：region not found or region conf version or split region problem）, and the cost will be high.

**Comment by kennytm** [comment] 2020-11-03 08:01
Duplicate of #256.

**Closed by kennytm** 2020-11-03 08:01 UTC
Labels: enhancement
