### ISSUE TITLE
Cluster restore stuck after completing DDL jobs

### ISSUE THREAD

**Issue by rachitmanit** [pingcap/br#348] opened 2020-06-11 21:28 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Motive is to restore full (entire cluster) backup within same cluster after dropping all user databases.
- Completed a cluster backup to S3:// based store (br backup full).
- drop all tables except `INFORMATION_SCHEMA, METRICS_SCHEMA, PERFORMANCE_SCHEMA and mysql`
- All the components (TiDB, TiKV, PD) are still running. No change in state.

2. What did you expect to see?
Expected cluster restore successfully.

3. What did you see instead?

Stuck with error in logs: "splitting regions failed retry, rpc error"

- Triggered `br restore full`, and **restore got stuck with log**:
<img width="1186" alt="Screenshot 2020-06-12 at 2 41 22 AM" src="https://user-images.githubusercontent.com/7613129/84440241-451ecc80-ac57-11ea-9c8f-868c9fe52b1e.png">

- Restore progress is also stuck at 0.00%:
<img width="1191" alt="Screenshot 2020-06-12 at 2 51 30 AM" src="https://user-images.githubusercontent.com/7613129/84440471-ad6dae00-ac57-11ea-9bb8-e32c7f2a7a28.png">

4. What version of BR and TiDB/TiKV/PD are you using?

**Comment by kennytm** [comment] 2020-06-12 06:02
Hi @rachitmanit. 

The error message is "Canceled", which suggests either there is another error before 02:23:53 or BR has received a SIGHUP signal. Are there any other WARN and ERROR logs around "splitting regions failed retry, rpc error"?

Thanks!

**Comment by rachitmanit** [comment] 2020-06-12 09:45
No @kennytm. There was no other error logs as i looked upon every component's long during the same time.

This is happening each time i apply restore on cluster. 
After dropping all added tables DDL and waiting for GC to complete delete ranges tasks (if any), I change tikv gc lifetime tp 24h and then i trigger cluster restore.

**Comment by rachitmanit** [comment] 2020-06-14 16:21
Restore successful on freshly created cluster but not old one.
Looks like the recommendation to restore Full backup on new cluster still holds.

You can add that 

**"Full/cluster restore can only be done on new clusters"**

As Table/Database restore is working on existing cluster too.

**Comment by 3pointer** [comment] 2020-06-18 02:07
The error is strange, could you provide complete logs of restore full cluster, this may help us to find the root cause why the restore failed. Thanks.

**Comment by rachitmanit** [comment] 2020-06-18 13:14
@3pointer above observations were from the test setup which is destroyed now.

**Comment by 3pointer** [comment] 2020-07-03 09:42
@rachitmanit this issue has been solved in #266, `v4.0.2` or later version of br will solve this problem. I'm going to close this issue, Thanks for the bug report.

**Closed by 3pointer** 2020-07-03 09:42 UTC
Labels: bug, status/discussion
