### ISSUE TITLE
Lightning supports TiKV RawKV mode

### ISSUE THREAD

**Issue by Little-Wallace** [pingcap/br#901] opened 2021-03-19 10:13 UTC
### Describe the feature you'd like:

I hope Lightning can support importing data to TiKV with RawKV format.

### Teachability, Documentation, Adoption, Migration Strategy:

The users of RawKV have to load data by `batch_put` interface. It is slowly and cost much IO flow caused by write-amplification of RocksDB.

**Comment by kennytm** [comment] 2021-03-19 13:50
duplicate of #764

**Closed by kennytm** 2021-03-19 13:50 UTC
Labels: type/feature-request
