### ISSUE TITLE
Error prompt "backup lock exists" is missing when run br with wrong argument "-s3.region"

### ISSUE THREAD

**Issue by fubinzh** [pingcap/br#1180] opened 2021-06-07 07:50 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Run br to do a backup, the "--s3.region" argument is wrongly typed as "-s3.region", missing one "-" (hyphen).

2. What did you expect to see?
The prompt should be clear and accurate when run br with wrong arguments 

3. What did you see instead?
The prompt is not clear, in this case it prompts " backup lock exists", this is not true, and it is misleading.

>>>
[root@centos76_vm v5.0.2]# ./br backup table --pd "172.16.6.183:2379" --db test --table student --storage "s3://tools-uw2/fb" --send-credentials-to-tikv=true -s3.region='us-west-2' --log-file test.log
Detail BR log in test.log
[2021/06/07 15:41:20.486 +08:00] [INFO] [collector.go:66] ["Table backup failed summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0]
Error: backup lock exists, may be some backup files in the path already: [BR:Common:ErrInvalidArgument]invalid argument

[root@centos76_vm br]# aws s3 ls s3://tools-uw2/fb --recursive

4. What version of BR and TiDB/TiKV/PD are you using?
TiDB: v5.0.2
[root@centos76_vm v5.0.2]# ./br -V
Release Version: v5.0.2
Git Commit Hash: ecfaf2ebc0465b570ad56374b69732a3c318a3e1
Git Branch: heads/refs/tags/v5.0.2
Go Version: go1.13
UTC Build Time: 2021-06-02 01:56:39
Race Enabled: false

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
[test.log](https://github.com/pingcap/br/files/6606887/test.log)

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by 3pointer** [comment] 2021-12-06 07:07
if input the wrong s3.region argument. the backup will use the default value of s3.region which is us-west-1. so I think this not a bug. 
I'll close it

**Closed by 3pointer** 2021-12-06 07:07 UTC
Labels: type/bug, severity/minor, component/backup
