### ISSUE TITLE
BR full restore won't rebase `auto_random` counter

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#241] opened 2020-04-21 06:41 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
BR didn't rebase auto_random after restore

    1.  set tidb config `auto_random` to true.
    2. `create table t(a int key auto_random); insert into t values (), (), ();`
    3. `br backup table --db t --table t --pd xxx -s xxx`
    4. `drop table t`
    5. `br restore table --db t --table t --pd xxx -s xxx` 
    6. `insert into t values (),(),();`

before backup:
```
MySQL [t]> select a & b'0000011111111111111111111111111' from t.t;
+----------------------------------------+
| a & b'0000011111111111111111111111111' |
+----------------------------------------+
|                                      1 |
|                                      2 |
|                                      3 |
+----------------------------------------+
```
2. What did you expect to see?

after restore:
```
select a & b'0000011111111111111111111111111' from t.t;
+----------------------------------------+
| a & b'0000011111111111111111111111111' |
+----------------------------------------+
|                                      4 |
|                                      5 |
|                                      6 |
|                                      1 |
|                                      2 |
|                                      3 |
+----------------------------------------+
```

3. What did you see instead?

after restore:
```
select a & b'0000011111111111111111111111111' from t.t;
+----------------------------------------+
| a & b'0000011111111111111111111111111' |
+----------------------------------------+
|                                      1 |
|                                      2 |
|                                      3 |
|                                      1 |
|                                      2 |
|                                      3 |
+----------------------------------------+
```

4. What version of BR and TiDB/TiKV/PD are you using?
master

**Comment by bb7133** [comment] 2020-04-24 04:12
The cause of this issue is that BR did not backup the "incremental part" of `auto_random`, and when restoring the data, TiDB cannot rebase the counter automatically since the restore is not in SQL layer.

In order to solve it, we need:

* For BR, backup the counter and try to restore it by an explicit rebase operation provided by TiDB(see below).
* For TiDB, provide a new DDL statement called 'ALTER TABLE ... AUTO_RANDOM', so the explicit rebase can be supported. The related PR has been proposed in (https://github.com/pingcap/parser/pull/823 and https://github.com/pingcap/tidb/pull/16750).

It will be fixed in release v3.1.1

**Closed** 2020-04-26 03:04 UTC
Labels: bug
