### ISSUE TITLE
When the incremental backup only has DDL, the incremental restore has problems

### ISSUE THREAD

**Issue by tongtongyin** [pingcap/br#652] opened 2020-12-18 09:49 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

If possible, provide a recipe for reproducing the error.
1.Create a table t1, do full backup to get backupData
2.Drop this table t1 , do incremental backup to get backupData-incr
3.Restore record in backupData
4. Restore record in backupData-incr
Note: Only one drop DDL operation between LastTS and backupTS. 

2. What did you expect to see?

The database should drop table t1 after restore record in backupData-incr.  

3. What did you see instead?

Table t1 still exists in the database after incremental recovery

4. What version of BR and TiDB/TiKV/PD are you using?

4.0.8

**Comment by 3pointer** [comment] 2020-12-21 12:45
This is by design. Only one drop table DDL won't work, in order to avoid data lost.
And if drop table & create table again, the origin drop DDL will be executed.

**Comment by tongtongyin** [comment] 2020-12-22 01:32
But when I create an empty table, perform an incremental backup.
During incremental restoration, the newly created empty table cannot be restored.

**Comment by 3pointer** [comment] 2020-12-22 02:41
> But when I create an empty table, perform an incremental backup.
> During incremental restoration, the newly created empty table cannot be restored.

In my test with v4.0.9 br, the empty table can be restored during incremental restoration, could you please provide more details about the operation and `br` version?

**Comment by tongtongyin** [comment] 2020-12-23 03:34
E.g:
Create an empty database test, create a table t1 in it, insert some data in table t1, and then perform a full backup to get backupData. The backup timestamp is TS1. Then create an empty table t2 in the test, without inserting any data, and perform incremental backup based on the timestamp TS1 to obtain backupDataIncr.

Delete the database test, first perform a full recovery based on backupData, and check that the table t1 exists in the database test. Then perform incremental recovery based on backupDataIncr, and check that the database test still has only table t1 and no table t2.

But there should be table t2.
![IMG_3518](https://user-images.githubusercontent.com/37565148/102956235-bb5b9000-4512-11eb-9b00-628b2048b58a.JPG)
![IMG_3519](https://user-images.githubusercontent.com/37565148/102956245-beef1700-4512-11eb-8759-d57ef754e7ac.JPG)
![IMG_3520](https://user-images.githubusercontent.com/37565148/102956251-c2829e00-4512-11eb-93b7-9a3904251961.JPG)
![IMG_3521](https://user-images.githubusercontent.com/37565148/102956258-c57d8e80-4512-11eb-920c-bcbd5ce75749.JPG)
![IMG_3522](https://user-images.githubusercontent.com/37565148/102956263-c8787f00-4512-11eb-854a-99b30403edb7.JPG)
![IMG_3523](https://user-images.githubusercontent.com/37565148/102956266-cadad900-4512-11eb-9e59-a3e63efff4a6.JPG)
![IMG_3524](https://user-images.githubusercontent.com/37565148/102956270-cd3d3300-4512-11eb-8652-9e6c47ca642f.JPG)
![IMG_3525](https://user-images.githubusercontent.com/37565148/102956278-d0d0ba00-4512-11eb-9be3-0417dd51d843.JPG)
![IMG_3526](https://user-images.githubusercontent.com/37565148/102956289-d4644100-4512-11eb-8443-169f917d50c0.JPG)

**Comment by 3pointer** [comment] 2020-12-24 09:26
That's strange.
could you try `tiup br validate decode --storage s3://tidb-test/BR/backupDataIncr` and find the decode json file to see whether `ddls` field is nil?

**Comment by 3pointer** [comment] 2020-12-25 07:04
oh, I found this [PR](https://github.com/pingcap/br/pull/468) fixed it, but didn't cherry-pick to release-4.0, so master br doesn't has such problem.

**Comment by tongtongyin** [comment] 2020-12-25 09:32
OK,THANKS

**Comment by 3pointer** [comment] 2021-01-25 03:19
https://github.com/pingcap/br/pull/658 merged, so we can close this issue for now.

**Closed by 3pointer** 2021-01-25 03:19 UTC
Labels: severity/major, type/bug
