### ISSUE TITLE
Br restore failed with the error of transport is closing when stop a tiflash node

### ISSUE THREAD

**Issue by lilinghai** [pingcap/br#1177] opened 2021-06-04 03:51 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
1. br restore data
2. add tiflash replica
3. kill -9 a tiflash node
```
2. What did you expect to see?
successfully

3. What did you see instead?
```
[2021/06/04 03:46:33.169 +00:00] [INFO] [collector.go:66] ["Full restore failed summary"] [total-ranges=4] [ranges-succeed=3] [ranges-failed=1] [split-region=5m38.22528811s] [restore-checksum=1m49.509667796s] [restore-ranges=15237] [unit-name=file] [error="rpc error: code = Unavailable desc = transport is closing"] [errorVerbose="rpc error: code = Unavailable desc = transport is closing\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15\ngithub.com/pingcap/br/pkg/restore.(*FileImporter).downloadSST\n\tgithub.com/pingcap/br@/pkg/restore/import.go:474\ngithub.com/pingcap/br/pkg/restore.(*FileImporter).Import.func1.1\n\tgithub.com/pingcap/br@/pkg/restore/import.go:314\ngithub.com/pingcap/br/pkg/utils.WithRetry\n\tgithub.com/pingcap/br@/pkg/utils/retry.go:46\ngithub.com/pingcap/br/pkg/restore.(*FileImporter).Import.func1\n\tgithub.com/pingcap/br@/pkg/restore/import.go:307\ngithub.com/pingcap/br/pkg/utils.WithRetry\n\tgithub.com/pingcap/br@/pkg/utils/retry.go:46\ngithub.com/pingcap/br/pkg/restore.(*FileImporter).Import\n\tgithub.com/pingcap/br@/pkg/restore/import.go:289\ngithub.com/pingcap/br/pkg/restore.(*Client).RestoreFiles.func2\n\tgithub.com/pingcap/br@/pkg/restore/client.go:617\ngithub.com/pingcap/br/pkg/utils.(*WorkerPool).ApplyOnErrorGroup.func1\n\tgithub.com/pingcap/br@/pkg/utils/worker.go:63\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1357"]
Error: rpc error: code = Unavailable desc = transport is closing
```
4. What version of BR and TiDB/TiKV/PD are you using?
v5.0.2

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by fubinzh** [comment] 2021-06-08 01:55
Similar issue seen when killing TiKV during br restore.

Steps:
1. br restore data
2. kill -9 one of the 3 TiKV in the cluster

Expected Results：
br restore should tolerate the TiKV loss, and succeed to finish the restore.

Actual Results:
br restore failed with error:

>>>
Error: No such file or directory (os error 2): [BR:KV:ErrKVDownloadFailed]download sst failed; No such file or directory (os error 2): [BR:KV:ErrKVDownloadFailed]download sst failed; rpc error: code = Unavailable desc = transport is closing

What version of BR and TiDB/TiKV/PD are you using?
v5.0.2

**Comment by 3pointer** [comment] 2021-07-06 03:52
Restore needs every store(TiKV + TiFlash) have the sst files to ingest, so it's by design in this situation. you can find the documents in https://docs.pingcap.com/tidb/stable/backup-and-restore-use-cases#backup-prerequisites, so I think it's not a major bug，I think it's more like a feature request.

**Comment by 3pointer** [comment] 2021-07-06 03:56
close due to duplicated: https://github.com/pingcap/br/issues/169

**Closed by 3pointer** 2021-07-06 03:56 UTC
Labels: component/restore, type/feature-request
